package main

import (
	"context"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"strings"
	"time"
)

// ─── Obsidian documentation ───────────────────────────────────────────────────
//
// When a swarm goal completes (all 7 Talos phases terminal), automatically
// writes a summary note to the Obsidian vault via the Local REST API plugin.
//
// Required env vars:
//   OBSIDIAN_API_URL      e.g. http://localhost:27123
//   OBSIDIAN_API_KEY      Local REST API auth key
//   OBSIDIAN_VAULT_FOLDER folder path in vault, e.g. Projects/TKN/Swarm
//
// Idempotent: only writes if obsidian_note_path IS NULL on the goal.

// maybeWriteObsidianNote creates an Obsidian note for a completed goal.
// Called as a goroutine from reconcileGoal. Uses full goal UUID to avoid collisions.
func maybeWriteObsidianNote(ctx context.Context, sessionID, goalID string) {
	apiURL := os.Getenv("OBSIDIAN_API_URL")
	apiKey := os.Getenv("OBSIDIAN_API_KEY")
	folder := os.Getenv("OBSIDIAN_VAULT_FOLDER")
	if apiURL == "" || apiKey == "" || folder == "" {
		return
	}

	// Idempotency: skip if already written
	var existingPath string
	database.QueryRowContext(ctx, //nolint:errcheck
		"SELECT COALESCE(obsidian_note_path,'') FROM swarm_goals WHERE id=?", goalID,
	).Scan(&existingPath)
	if existingPath != "" {
		return
	}

	// Build note content
	note, notePath := buildObsidianNote(ctx, sessionID, goalID, folder)
	if note == "" {
		return
	}

	// Write with timeout to avoid blocking reconcile goroutine
	writeCtx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()

	url := strings.TrimRight(apiURL, "/") + "/vault/" + notePath
	req, err := http.NewRequestWithContext(writeCtx, "PUT", url, strings.NewReader(note))
	if err != nil {
		log.Printf("swarm/obsidian: build request: %v", err)
		return
	}
	req.Header.Set("Authorization", "Bearer "+apiKey)
	req.Header.Set("Content-Type", "text/markdown")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		log.Printf("swarm/obsidian: write note for goal %s: %v", goalID[:8], err)
		return
	}
	defer resp.Body.Close()
	io.Copy(io.Discard, resp.Body) //nolint:errcheck

	if resp.StatusCode >= 400 {
		log.Printf("swarm/obsidian: vault returned %d for goal %s", resp.StatusCode, goalID[:8])
		return
	}

	// Record note path
	database.ExecContext(ctx, //nolint:errcheck
		"UPDATE swarm_goals SET obsidian_note_path=? WHERE id=?", notePath, goalID)

	log.Printf("swarm/obsidian: note written for goal %s → %s", goalID[:8], notePath)
}

// buildObsidianNote constructs the markdown content and file path for a goal note.
func buildObsidianNote(ctx context.Context, sessionID, goalID, folder string) (string, string) {
	var desc string
	database.QueryRowContext(ctx, //nolint:errcheck
		"SELECT description FROM swarm_goals WHERE id=?", goalID,
	).Scan(&desc)
	if desc == "" {
		return "", ""
	}

	// Collect per-phase task summaries
	rows, err := database.QueryContext(ctx,
		`SELECT COALESCE(phase,''), title, COALESCE(confidence,0)
		 FROM swarm_tasks
		 WHERE goal_id=? ORDER BY phase_order ASC NULLS LAST, created_at ASC`,
		goalID,
	)
	type phaseRow struct {
		phase      string
		title      string
		confidence float64
	}
	var phases []phaseRow
	if err == nil {
		defer rows.Close()
		for rows.Next() {
			var p phaseRow
			rows.Scan(&p.phase, &p.title, &p.confidence)
			phases = append(phases, p)
		}
	}

	date := time.Now().Format("2006-01-02")
	var sb strings.Builder
	fmt.Fprintf(&sb, "# Swarm Goal: %s\n\n", truncate(desc, 80))
	fmt.Fprintf(&sb, "**Date:** %s  \n", date)
	fmt.Fprintf(&sb, "**Goal ID:** `%s`  \n", goalID)
	fmt.Fprintf(&sb, "**Session:** `%s`  \n\n", sessionID[:8])
	fmt.Fprintf(&sb, "## Goal Description\n\n%s\n\n", desc)

	if len(phases) > 0 {
		fmt.Fprintf(&sb, "## Talos Phases\n\n")
		for _, p := range phases {
			label := p.phase
			if label == "" {
				label = "task"
			}
			conf := ""
			if p.confidence > 0 {
				conf = fmt.Sprintf(" (confidence: %.0f%%)", p.confidence*100)
			}
			fmt.Fprintf(&sb, "- **%s**%s — %s\n", label, conf, p.title)
		}
		fmt.Fprintf(&sb, "\n")
	}

	fmt.Fprintf(&sb, "## Outcome\n\nAll Talos phases completed. Goal marked complete by swarm orchestrator.\n")
	fmt.Fprintf(&sb, "\n---\n*Generated by SwarmOps on %s*\n", date)

	// Sanitise goal ID for use as filename (full UUID, safe characters only)
	filename := strings.ReplaceAll(goalID, "/", "-")
	notePath := strings.TrimRight(folder, "/") + "/goal-" + filename + ".md"
	return sb.String(), notePath
}
