// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: execution_milestones.sql

package db

import (
	"context"
)

const createExecutionMilestone = `-- name: CreateExecutionMilestone :one
INSERT INTO execution_milestones (execution_id, text)
VALUES (?, ?)
RETURNING id, execution_id, text, created_at
`

type CreateExecutionMilestoneParams struct {
	ExecutionID int64  `db:"execution_id" json:"execution_id"`
	Text        string `db:"text" json:"text"`
}

func (q *Queries) CreateExecutionMilestone(ctx context.Context, arg CreateExecutionMilestoneParams) (ExecutionMilestone, error) {
	row := q.db.QueryRowContext(ctx, createExecutionMilestone, arg.ExecutionID, arg.Text)
	var i ExecutionMilestone
	err := row.Scan(
		&i.ID,
		&i.ExecutionID,
		&i.Text,
		&i.CreatedAt,
	)
	return i, err
}

const listMilestonesByExecutionID = `-- name: ListMilestonesByExecutionID :many
SELECT id, execution_id, text, created_at FROM execution_milestones
WHERE execution_id = ?
ORDER BY created_at DESC
LIMIT 10
`

func (q *Queries) ListMilestonesByExecutionID(ctx context.Context, executionID int64) ([]ExecutionMilestone, error) {
	rows, err := q.db.QueryContext(ctx, listMilestonesByExecutionID, executionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExecutionMilestone
	for rows.Next() {
		var i ExecutionMilestone
		if err := rows.Scan(
			&i.ID,
			&i.ExecutionID,
			&i.Text,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentMilestoneTexts = `-- name: GetRecentMilestoneTexts :many
SELECT text FROM execution_milestones
WHERE execution_id = ?
ORDER BY created_at DESC
LIMIT 10
`

func (q *Queries) GetRecentMilestoneTexts(ctx context.Context, executionID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getRecentMilestoneTexts, executionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var text string
		if err := rows.Scan(&text); err != nil {
			return nil, err
		}
		items = append(items, text)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
